Creation internalService
ted7007/OrdersApp pull request #1
Opened 2022-09-25 13:15 UTC by ted7007

2022-09-28 01:06 UTC, EvoMGenius requested changes
Пиши в вк как закончишь, я приглашение то не сразу увидел на почте, а изменения еще позже могу заметить

2022-09-28 01:06 UTC, EvoMGenius commented on InternalService/Properties/launchSettings.json
> +        "MySQLOptions:Password":"password"
Привыкай сразу всю инфу о таких конфиг данных выносить в элементы окружения.

2022-09-28 01:06 UTC, EvoMGenius commented on docker-compose.yml
> +      - "3308:3306"
почему 3308?

2022-09-28 01:06 UTC, EvoMGenius commented on docker-compose.yml
> +        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
зачем?

2022-09-28 01:06 UTC, EvoMGenius commented on docker-compose.yml
> +    image: mysql:8.0
мы же вроде на постгрес договаривались?

2022-10-07 13:38 UTC, ted7007 commented on InternalService/Properties/launchSettings.json
> +        "MySQLOptions:Password":"password"
Если имеешь ввиду environment variables, то это они и есть) Мне проще их здесь объявить.
Зря я закоммитил этот файл, уберу на следующем коммите.

2022-10-07 15:13 UTC, ted7007 commented on InternalService/Properties/launchSettings.json
> +        "MySQLOptions:Password":"password"
Не буду удалять) Для удобства оставляю его в системе контроля, он используется только на стадии development

2022-10-19 10:17 UTC, merged