Creation tests for InternalService
ted7007/OrdersApp pull request #3
Opened 2022-10-08 06:12 UTC by ted7007

2022-10-08 07:28 UTC, EvoMGenius requested changes

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +          Assert.IsTrue(result.Count() == 2);
можешь замокать спокойно список заказов. тебе не нужна тут конретика. поэтому и количество не нужно будет смотреть. плюс сразу добавь поисковые параметры. чтобы можно было искать по критериям определенные заказы. у тебя получается концептуально не верно уже идет метод получения заказов. это должен быть не GetAll а getList или что-то типа того. ибо в этот метод можно спокойно вклеить поиск заказов по параметрам определенным. 
1) Сделать возможным поиск заказов по параметрам
2) Переименовать getAll -> getList
3) Переделать в соответствии с этим тест.

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        var testOrder = new Order() { Id = testId };
можно это все замокать. теебе не надо лазить в сущность за id. ибо ты напрямую уже передашь этот id в обхект взаимодействующий с бд. там уже полюбому все сработает так. как должно.

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        _repository.Setup(r => r.Get(testId)).Returns(testOrder);
нельзя сделать что-то типа r.Get(any()).returns...
чтобы не уточнять айди в сценарии мока.

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        var service = new OrderService(_repository.Object, _dishService.Object, _mapper);
ты постоянно объявляешь сервис в тестках. вынеси его как поле класса теста

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        Assert.IsTrue(result.Id == testId);
не нужно

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        _repository.Verify(r => r.Get(testId));
а это не уберай. это как раз оставь как проверку того, что у тебя вызвался метод репозитория с этим айди. тут норм

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +       var testArgument = GetTestArgument();
Create Arguments

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +       service.Create(testArgument);
где получение результата?

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +       _dishService.Verify(s => s.Get(It.IsAny<Guid>()));
Где сравнение полученного результата с ожидаемым?

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        //Assert
arrange

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +                Is<Order>(order => order.Price == expectedPrice )));
не понимаю смысл

2022-10-08 07:28 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +                    new() { Id = Guid.Parse("d0e5d24e-ea32-4262-8b32-f273341c6ef4") }
в идеале это все перенести в json файлы какие-нибудь. и есть есть ResourceUtils какой-нибудь. считать с него. но не обязательно. можно и так оставить

2022-10-08 07:39 UTC, ted7007 commented on InternalServiceTests/OrderServiceTests.cs
> +                Is<Order>(order => order.Price == expectedPrice )));
Проверка логики, что в заказ собирается цена равная сумме цен блюд

2022-10-08 07:42 UTC, EvoMGenius commented on InternalServiceTests/OrderServiceTests.cs
> +        var service = new OrderService(_repository.Object, _dishService.Object, _mapper);
в таком случае. любые постиоения ожидаемых результатов должны быть в assert блоке.

2022-10-13 06:16 UTC, EvoMGenius approved these changes

2022-10-13 12:40 UTC, merged