Integration tests
ted7007/OrdersApp pull request #4
Opened 2022-10-18 12:19 UTC by ted7007

2022-10-18 12:24 UTC, EvoMGenius requested changes
чет нитгде не вижу такого момента как изначальный датасет и ожидаемый. ну да ладно. может у вас и нет такого

2022-10-18 12:24 UTC, EvoMGenius commented on InternalServiceIntegrationTests/OrderControllerTests.cs
> +     private readonly ApplicationContext _context;
подгрузил весь контекст приложения??? ммм не знаю как у вас но у нас в жабе это пиздец стремное решеньеце

2022-10-18 12:29 UTC, EvoMGenius requested changes

2022-10-18 12:29 UTC, EvoMGenius commented on InternalServiceIntegrationTests/OrderControllerTests.cs
> +          var expectedPrice = 400;
плоховасто что в хардкожено. но даже если так вхардкодил. почему в последнем ассерде это 400 туда не запихал?

2022-10-18 12:29 UTC, EvoMGenius commented on InternalServiceIntegrationTests/OrderControllerTests.cs
> +         Assert.True(actualOrder.Id != Guid.Empty);
вроде выглядит бесполезным. ибо id заказа у тебя всегда создасттся. он ведь гинерится при создании заказа

2022-10-18 12:29 UTC, EvoMGenius commented on InternalServiceIntegrationTests/OrderControllerTests.cs
> +               .With(o => o.Dishes, new List<Dish>())
а вообще интеграшки не плохо было бы данными наполнить. а не пустыми листами. чтобы посмотреть какие изменения внутри кода могут быть оказаны на данные

2022-10-18 12:48 UTC, ted7007 commented on InternalServiceIntegrationTests/OrderControllerTests.cs
> +               .With(o => o.Dishes, new List<Dish>())
` _orderCustomizationComposer`
это настроенный экземпляр Fixture(там обязательное условие UTC времени в этой настройке),
а Fixture сам наполняет рандомными валидными по типу данными, за исключением исключительных полей которые я сам настраиваю

2022-10-19 10:16 UTC, ted7007 commented
Остался вопрос по поводу использования контекста в тестах. Принято решение игнорировать его.

2022-10-19 10:17 UTC, merged